-- @description Articulation Scripts
-- @author Saxmand
-- @package Articulation Scripts
-- @version 0.8.5
-- @about
--   A complete system for the MOST advanced articulation scripts
-- @provides
--   Functions/*.lua
--   Functions/*.dat
--   Functions/Helpers/*.lua
--   [main] Saxmand_Articulation_Script Creator.lua
--   [main] Saxmand_Articulation_License Window.lua
--   [main] Saxmand_Articulation_Scripts List.lua
--   [main] Saxmand_Articulation_Background Server.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_Keyboard Trigger Surface.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_List Overview Surface.lua
-- @changelog
--   + removed unnessesary log
--   + note input can only do true note input combinations. It's now also possible to use s/S for sharp (#) or f/F for flat (b) 