-- @description Articulation Scripts
-- @author Saxmand
-- @package Articulation Scripts
-- @version 1.1.7
-- @about
--   A complete system for the MOST advanced articulation system
-- @provides
--   articulation_scripts_library.txt
--   Functions/*.lua
--   Functions/*.dat
--   Functions/Helpers/*.lua
--   Functions/pre_delay_lib/*.lua
--   [main] Saxmand_Articulation_Script Creator.lua
--   [main] Saxmand_Articulation_License Window.lua
--   [main] Saxmand_Articulation_Background Server.lua
--   [main] Saxmand_Articulation_Scripts Browser.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_Keyboard Trigger Surface.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_List Overview Surface.lua
-- @changelog
--   + incrementing not numbers from 1 instead of 0 (like titles)
--   + trigger on every notes gives better user experience I think and is set to true as default again
--   + trigger on every notes instrument settings is respected when creating articulation scripts