-- @description Articulation Scripts
-- @author Saxmand
-- @package Articulation Scripts
-- @version 0.9.4
-- @about
--   A complete system for the MOST advanced articulation system
-- @provides
--   Functions/*.lua
--   Functions/*.dat
--   Functions/Helpers/*.lua
--   [main] Saxmand_Articulation_Script Creator.lua
--   [main] Saxmand_Articulation_License Window.lua
--   [main] Saxmand_Articulation_Scripts List.lua
--   [main] Saxmand_Articulation_Background Server.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_Keyboard Trigger Surface.lua
--   [main=midi_editor,midi_inlineeditor,main] Saxmand_Articulation_List Overview Surface.lua
-- @changelog
--   + articulation scripts change articulation immediately when changing via surfaces or on jsfx (so no note on required)
--   + unified version numbering
--   + added creator version to name
--   + internal on dev using same path as users
--   + adding more global switches to settings on articulation surfaces 
--   + changed default of "Trigger articulaion on every note" 